name: Feature request
description: Suggest an idea for Stati
title: "[feat]: "
labels: ["type:feat"]
body:
  type: textarea
  attributes:
  label: Problem
  description: What problem are you trying to solve?

  type: textarea
  attributes:
  label: Proposal
  description: What do you suggest we add or change?

  type: textarea
  attributes:
  label: Alternatives