/**
 * Tailwind CSS setup processor for the Stati scaffolder.
 * Generates Tailwind configuration files and starter CSS for new projects.
 * @module create-stati/tailwind-processor
 */

import { DEPENDENCY_VERSIONS } from './constants.js';
import type { ProcessorResult } from './types.js';

/**
 * Generate Tailwind CSS setup files and dependencies.
 * Returns all files and configuration needed for Tailwind support.
 *
 * @returns Processor result with files, dependencies, and scripts
 *
 * @example
 * ```typescript
 * const tailwindSetup = setupTailwind();
 * // tailwindSetup.files contains: tailwind.config.js, src/styles.css
 * // tailwindSetup.devDependencies contains: { tailwindcss: '^3.4.0', ... }
 * // tailwindSetup.scripts contains: { 'build:css': '...', dev: '...', build: '...' }
 * ```
 */
export function setupTailwind(): ProcessorResult {
  return {
    files: new Map([
      ['tailwind.config.js', generateTailwindConfig()],
      ['src/styles.css', generateTailwindCSS()],
    ]),
    devDependencies: {
      tailwindcss: DEPENDENCY_VERSIONS.tailwindcss,
      autoprefixer: DEPENDENCY_VERSIONS.autoprefixer,
      postcss: DEPENDENCY_VERSIONS.postcss,
    },
    scripts: {
      'build:css': 'tailwindcss -i src/styles.css -o public/styles.css --minify',
      'copy:css':
        "node -e \"require('node:fs').copyFileSync('public/styles.css','dist/styles.css')\"",
      build: 'stati build && npm run build:css && npm run copy:css',
      dev: 'stati dev --tailwind-input src/styles.css --tailwind-output public/styles.css',
    },
  };
}

/**
 * Generate tailwind.config.js content for Stati projects.
 * Configured to scan site directory and Stati's dynamic class inventory.
 *
 * @returns JavaScript content for tailwind.config.js
 */
function generateTailwindConfig(): string {
  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './site/**/*.{md,eta,html}',
    './.stati/tailwind-classes.html', // Auto-generated by Stati for dynamic classes
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;
}

/**
 * Generate starter Tailwind CSS input file.
 * Includes base directives and common component classes.
 *
 * @returns CSS content for src/styles.css
 */
function generateTailwindCSS(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .logo {
    @apply text-xl font-bold text-blue-600 no-underline;
  }

  .skip-link {
    @apply absolute -top-10 left-1 bg-black text-white p-2 no-underline z-50;
  }

  .skip-link:focus {
    @apply top-1;
  }
}
`;
}
